### ISSUE TITLE
Unbounded options

### ISSUE THREAD

**Issue by jadekler** [GoogleCloudPlatform/grpc-gcp-go#11]
- When ChannelPoolConfig.MaxSize == 0, it should be treated as "unbounded". (Currently it's treated as 10](https://github.com/GoogleCloudPlatform/grpc-gcp-go/blob/master/grpcgcp/gcp_balancer.go#L36-L38).
- When ChannelPoolConfig.MaxConcurrentStreamsLowWatermark == 0, it should be treated as "unbounded". (Currently it's treated as 100](https://github.com/GoogleCloudPlatform/grpc-gcp-go/blob/master/grpcgcp/gcp_balancer.go#L36-L38). That is: channels should be spun up based on network signals, such as MAX_CONCURRENT_STREAMS.
- ChannelPoolConfig.MaxConcurrentStreamsLowWatermark == 0 (unbounded) should explicitly be the recommended default. There is no technical reason to my knowledge that <MAX_CONCURRENT_STREAMS should be on a single TCP connection.

**Comment by WeiranFang** [comment]
Thanks for bringing that up. The checker for https://github.com/GoogleCloudPlatform/grpc-gcp-go/blob/master/grpcgcp/gcp_picker.go#L69 and https://github.com/GoogleCloudPlatform/grpc-gcp-go/blob/master/grpcgcp/gcp_picker.go#L76 is just to cover the cases where user doesn't specify anything for those two values, because the generated proto class by default returns '0' for both GetMaxSize() and GetMaxConcurrentStreamsLowWatermark(), and honestly I don't know how I can check whether the '0' is specified by user or it's just come from the default unset value.

For MaxConcurrentStreamsLowWatermark, I made this default as 100 is just because of the max 100 concurrent streams bottleneck caused by GFE configuration. But if there's no consideration other than that, I can make it unbounded as default.

For MaxSize, is there any potential memory concerns if we set this as "unbounded"?  And if '0' is treated as "unbounded", I'm not sure how to differentiate whether this is the default unset "0", or is specified by the user.

Looking forward to hear your thoughts:)

**Comment by jadekler** [comment]
> I don't know how I can check whether the '0' is specified by user or it's just come from the default unset value.

Typically you'd use a pointer for that (nil, 0, >0). However, in this case, 0 is meaningless so I think it's fine to treat 0 as unbounded.

> For MaxConcurrentStreamsLowWatermark, I made this default as 100 is just because of the max 100 concurrent streams bottleneck caused by GFE configuration.

Isn't that handled by other layers in gRPC anyway? @menghanl @dfawley 

> For MaxSize, is there any potential memory concerns if we set this as "unbounded"? And if '0' is treated as "unbounded", I'm not sure how to differentiate whether this is the default unset "0", or is specified by the user.

I don't think so. Ideally MaxConcurrentStreamsLowWatermark would be 0 (unbounded) and we'd just create new streams when we reach MAX_CONCURRENT_STREAMS. That is, the number should be very low in a normal case.

In the non-normal case, there's still not really any problems. Spinning up a bunch of connections is kind of unfortunate in terms of allocations (in-program and in kernel) but certainly isn't illegal.

**Comment by dfawley** [comment]
> Isn't that handled by other layers in gRPC anyway?

It depends on what you're looking to do.  We respect the server's max concurrent streams setting in accordance with the HTTP/2 spec.  However, we will block an RPC if the transport picked would exceed its allowable stream count limit.  There's no way for a balancer to choose a different transport if the preferred transport is already at its maximum, and there is currently no mechanism for conveying the maximum count back to the balancer.

**Comment by WeiranFang** [comment]
> Typically you'd use a pointer for that (nil, 0, >0). However, in this case, 0 is meaningless so I think it's fine to treat 0 as unbounded.
So in https://github.com/GoogleCloudPlatform/grpc-gcp-go/blob/master/grpcgcp/grpc_gcp/grpc_gcp.pb.go#L144 the method will always return non-nil values (if unset 0 will be returned), so if user doesn't set the maxSize, then it will be read as 0, which means the maxSize will be "unbounded" by default. But I think it's fine as long as I document it, and you are right, 0 is totally meaningless.

**Comment by dfawley** [comment]
FWIW, the proto3 workaround for this problem is boxed types, e.g. https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Int32Value.  The wrapping message can be unset, so you can distinguish between unset and set-to-default.

**Comment by jadekler** [comment]
> It depends on what you're looking to do. We respect the server's max concurrent streams setting in accordance with the HTTP/2 spec. However, we will block an RPC if the transport picked would exceed its allowable stream count limit. There's no way for a balancer to choose a different transport if the preferred transport is already at its maximum, and there is currently no mechanism for conveying the maximum count back to the balancer.

Gotcha. 100 as the default makes sense to me then.

@WeiranFang what happens if a user sets value >100? Maybe it's good to bound it to 100 and document the bound. "Any value over 100 will be rounded down to 100", or something?

**Comment by WeiranFang** [comment]
> what happens if a user sets value >100? Maybe it's good to bound it to 100 and document the bound. "Any value over 100 will be rounded down to 100", or something?

I believe if the concurrent streams reach 100 or more in one connection, any new rpc request on that connection will just hang there. I'm not sure whether we want to round down 100+ to 100 for this value, since this value anyway is a soft limit. WDYT?

**Comment by jadekler** [comment]
> I believe when the concurrent streams reach 100 or more in one connection, any new rpc request on that connection will just hang there. I'm not sure whether we want to round down 100+ to 100 for this value, since this value anyway is a soft limit. WDYT?

My feeling is that nobody would want their requests to hang in lieu of spinning out a new connection. There's little downside to spinning out a new connection (TCP init and warm up, which isn't that big of a deal if infrequent) compared to potentially building up a large backlog of requests. So, I'm in favour of rounding down.

**Comment by WeiranFang** [comment]
> My feeling is that nobody would want their requests to hang in lieu of spinning out a new connection. There's little downside to spinning out a new connection (TCP init and warm up, which isn't that big of a deal if infrequent) compared to potentially building up a large backlog of requests. So, I'm in favour of rounding down.

Sounds good. So to confirm:
MaxSize: default is 0, and 0 means unbounded.
MaxStreamsLowWatermark: default is 100 (and 100+ will be rounded down to 100), and also 0 means unbounded.

Does that look good?

**Comment by jadekler** [comment]
> MaxStreamsLowWatermark: [...] 0 means unbounded.

I had originally thought that this could result in letting something like MAX_CONCURRENT_STREAMS take over. Basically to let the transport figure it out. It _sounds_ like Doug's saying that's not possible. If that's the case, I would default to 100 if users set any value outside [1, 100]. 

My interpretation of @dfawley answer might be wrong, though, so would be good to double check.

**Comment by WeiranFang** [comment]
I feel like rounding down the value in our code has some limitations. Since the current 100 maximum value is also a configurable value on GFE side, if somehow GFE changes this limit, then this round down logic also needs to be updated. Do you think it would be better for the service owner (e.g. spanner, bigtable) to have more flexibility when setting this MaxStreamsLowWatermark value? For example, they can decide to increase this value if they are aware that GFE somehow supports more concurrent streams.

**Comment by jadekler** [comment]
I don't think service owners should ever adjust this value, since the GFE is cross services. Currently this default / max lives in grpc-gcp (this repo), which means you+grpc team own it. I actually think that's as close as you can get to the right canonical owner if you're unable to use MAX_CONCURRENT_STREAMS.

The actually correct solution, though, is to somehow use MAX_CONCURRENT_STREAMS.
