### ISSUE TITLE
Is channel analagous to connection?

### ISSUE THREAD

**Issue by jadekler** [GoogleCloudPlatform/grpc-gcp-go#14]
Does each channel result in one connection, or is it still possible for a single channel to result in multiple connections? (for example, when a DNS resolver returns multiple IPs).

Regardless of the question, we should probably make this distinction (1=1 or 1=*) clear in docs. I think it's going to be easy for people to conflate channel pool with connection pool.

**Comment by WeiranFang** [comment]
In case of Go, since we are implementing a pool of subconns, a channel pool actually means a connection pool. I'll document this in doc. Thanks for mentioning that.
